name: vagrant

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: vagrant install
        run: |
          sudo apt install vagrant
          vagrant plugin install vagrant-vbguest
          sudo apt install virtualbox
      - name: vagrant init
        run: |
          vagrant init bento/ubuntu-19.10
          less Vagrantfile
          vagrant init -f -m bento/ubuntu-19.10
      - name: vagrantfile edit
        run: |
          mkdir shared
          cat > Vagrantfile <<EOF
          \$script = <<-SCRIPT
          sudo apt install docker.io -y
          sudo docker pull fastide/ubuntu:19.04
          sudo docker create -ti --name fastide fastide/ubuntu:19.04 bash
          sudo docker cp fastide:/home/developer /home/
          sudo useradd developer
          sudo usermod -aG sudo developer
          echo "developer:developer" | sudo chpasswd
          sudo chown -R developer /home/developer
          SCRIPT
          EOF
          cat >> Vagrantfile <<EOF

          Vagrant.configure("2") do |config|

          config.vagrant.plugins = ["vagrant-vbguest"]
          EOF
          cat >> Vagrantfile <<EOF

            config.vm.box = "bento/ubuntu-19.10"
            config.vm.network "public_network"
            config.vm.synced_folder('shared', '/vagrant', type: 'rsync')
          
            config.vm.provider "virtualbox" do |vb|
              vb.gui = true
              vb.memory = "2048"
            end

            config.vm.provision "shell", inline: \$script, privileged: true

            config.ssh.extra_args = "-tt"

          end
          EOF
      - name: vagrant validate
        run: |
          vagrant validate
          vagrant status
      - name: vagrant up
        run: |
          VAGRANT_DETECTED_OS=cygwin
          vagrant up --provider virtualbox
      - name: vagrant destroy
        run: |
          vagrant destroy --force
